### PR TITLE
Cr eventlist

### PR DESCRIPTION
**Pull request by cresuta**
- /event sub-directory of /components was created, along with all necessary files   
- event list page displays all events in database.json, with react-bootstrap card component styling for each
- the event that is upcoming on the agenda (event:first-child) has specific css styling to indicate that is is next in line for all events
- all events are sorted by ascending date
- add new event btn correctly renders an event form and upon submitting the new event, will redirect to /events and update
-make sure json server is running with react server before testing
-if you want to test locally...
git fetch -a
in the terminal
git checkout [branch-to-test]

### CODE REVIEW

**Review by andy-birt — APPROVED** [review]
Looks good man 😃

**Review by heavenburdette1988 — APPROVED** [review]
Looks good!

**Review by andy-birt — APPROVED** [review]
Awesome!

**Review by heavenburdette1988 — APPROVED** [review]
All good!

**Pull request merged**
